services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9100:9000"   # API
      - "9001:9001"   # Console
    environment:
      - MINIO_ROOT_USER=vokov
      - MINIO_ROOT_PASSWORD=805235io
      # Додайте ці змінні для кращої роботи з S3 API
      - MINIO_BROWSER=on
      - MINIO_DOMAIN=apiminio.exodus.pp.ua
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mcp-server:
    image: quay.io/minio/aistor/mcp-server-aistor:latest
    container_name: mcp-server
    ports:
      - "8090:8090"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=vokov
      - MINIO_SECRET_KEY=805235io
      - MINIO_USE_SSL=false
    depends_on:
      - minio
    restart: unless-stopped
    command:
      [
        "--allow-admin",
        "--allow-delete",
        "--allow-write",
        "--http",
        "--http-port", "8090"
      ]

volumes:
  portainer_data: